--- #YAML:1.0
name:                TM-Easy
version:             0.02
abstract:            Topic Maps, Easy Usage
license:             ~
author:              
    - Robert Barta <rho@devc.at>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0.47
    TM:                            1.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
